version: '3'
services:
  redis-server-master:
    restart: always
    container_name: redis-server-master
    image: redis:alpine
    ports:
      - 16379:6379
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - /data/redis1-data:/data
      - ./redis-master.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis_net
    environment:
      TZ: "Asia/Shanghai"
  # redis-server-slave-1:
  #   restart: always
  #   container_name: redis-server-slave-1
  #   image: redis:alpine
  #   ports:
  #     - 6380:6379
  #   command: redis-server /usr/local/etc/redis/redis.conf 
  #   volumes:
  #     - /data/redis2-data:/data
  #     - ./redis-slave1.conf:/usr/local/etc/redis/redis.conf
  #   networks:
  #     - redis_net
  #   environment:
  #     TZ: "Asia/Shanghai"
  #   depends_on:
  #     - redis-server-master
  # redis-server-slave-2:
  #   restart: always
  #   container_name: redis-server-slave-2
  #   image: redis:alpine
  #   ports:
  #     - 6381:6379
  #   command: redis-server /usr/local/etc/redis/redis.conf 
  #   volumes:
  #     - /data/redis3-data:/data
  #     - ./redis-slave2.conf:/usr/local/etc/redis/redis.conf
  #   networks:
  #     - redis_net
  #   environment:
  #     TZ: "Asia/Shanghai"
  #   depends_on:
  #     - redis-server-master
networks:
  redis_net:
    external: true
    
    
  